---
# name of instances
name: argocd

# this is for argo type deployments of this chart (set to true)
ignoreHelmHooks: false

# add to this list to deploy team instances to these namespaces
namespaces:
- labs-ci-cd

# operator manages upgrades
operator:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  sourceName: redhat-operators
  sourceNamespace: openshift-marketplace
  disableDefaultArgoCD: true

# see the TEAM_DOCS.md for more information
teamInstancesAreClusterScoped: true

# adding your secrets for git access or other repository credentials
secrets: []
# EXAMPLE ...
# secrets:
#   - name: git-auth
#     username: 'user'
#     password: 'pass1234'
#     sshPrivateKey: ''

# https://argocd-operator.readthedocs.io/en/latest/reference/argocd/
argocd_cr:
  # version: v2.10.5 # set this if you want the upstream containers instead
  applicationSet: {}
  notifications:
    enabled: true
  rbac:
    defaultPolicy: 'role:admin'
    policy: |
      g, system:cluster-admins, role:admin
    scopes: '[groups]'
  resourceExclusions: |
    - apiGroups:
        - tekton.dev
      clusters:
        - '*'
      kinds:
        - TaskRun
        - PipelineRun
  server:
    ingress:
      enabled: false
    route:
      enabled: true
      tls:
        termination: reencrypt
  sso:
    dex:
      openShiftOAuth: true
    provider: dex

  initialRepositories: |
    - name: ubiquitous-journey
      url: https://github.com/demo-gitops/ubiquitous-journey.git
    - name: demo-gitops
      type: helm
      url: https://demo-gitops.github.io/helm-charts

  # configure your repo credential template (override this)
  repositoryCredentials: null
  # EXAMPLE
  # repositoryCredentials: |
  #   - url: https://gitlab-ce.apps.openshift-498-bd8hw.do500.redhatlabs.dev
  #     type: git
  #     passwordSecret:
  #       key: password
  #       name: git-auth
  #     usernameSecret:
  #       key: username
  #       name: git-auth
