apiVersion: v2
name: update-clusterversion
description: A Helm chart to update OpenShift ClusterVersion
home: https://github.com/demo-gitops/helm-charts
version: 1.0.0
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
keywords:
  - configuration
