apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apply
  namespace: {{ .Values.application.environments.cicd }}
spec:
  workspaces:
  - name: source
  - name: shared
  steps:
    - name: helm-apply
      image: registry.redhat.io/openshift4/ose-cli:latest@sha256:7ea824531b593b2ec0da05557d5cd2565c3525c51c9007f85e9510b27f38b13f
      resources: {}
      workingDir: /workspace/source/{{ .Values.pipeline.build.s2i.context }}
      script: |
        #!/bin/sh
        if [ -d "chart" ]; then
          /workspace/shared/helm template -f chart/values.yaml chart | oc apply -f-
        else
          echo "Chart does not exist"
          exit 0
        fi
      securityContext:
        runAsUser: 0
